'use client'

import Link from 'next/link'
import { useState } from 'react'

// ─────────────────────────────────────────────────────────────────────────────
// Learning Journey features — the headline pitch of this page. Maps live in
// here as ONE feature among many; the full map catalogue further down the
// page is a "browse what's already built" preview, not the main pitch.
// ─────────────────────────────────────────────────────────────────────────────

interface JourneyFeature {
  icon: string
  title: string
  description: string
  color: string
}

const JOURNEY_FEATURES: JourneyFeature[] = [
  {
    icon: '📖',
    title: 'AI study notes for every topic',
    description: 'Rich, easy-to-read notes for all 280+ UPSC topics — generated by AI with key concepts, timelines, comparisons, mind maps and exam strategy. Tap any underlined term to see what it means.',
    color: '#818cf8',
  },
  {
    icon: '🎯',
    title: 'Practice real PYQs',
    description: '3,000+ Previous Year Questions from 2011 – 2024 across all GS papers. Instant feedback, hearts, and a 5-level mastery system per topic so you know exactly where you stand.',
    color: '#f97316',
  },
  {
    icon: '✨',
    title: "Your AI mentor's daily tip",
    description: 'Every day your AI mentor reads your progress, focus subjects, streak and pace — and writes a personal tip telling you exactly what to do today, in plain English.',
    color: '#a78bfa',
  },
  {
    icon: '🎚️',
    title: 'My Focus Subjects',
    description: 'Pick the subjects you want to study most. The AI prioritises them in your daily tip, Your Next Step and Up Next — and re-calibrates the moment you change them.',
    color: '#67e8f9',
  },
  {
    icon: '✍️',
    title: 'Subject-specific Mains frameworks',
    description: "Different answer-writing blueprints for History, Polity, Economy, Environment, Ethics, Essay and more — drawn from actual UPSC Mains PYQs and tested with toppers' scripts.",
    color: '#60a5fa',
  },
  {
    icon: '🗺️',
    title: 'Interactive maps',
    description: 'Visualise any geography, history or policy topic on a live AI-generated map. Tap any place inside your study notes to plot it instantly.',
    color: '#34d399',
  },
  {
    icon: '🔥',
    title: 'Daily goals & streaks',
    description: 'Set a daily reading + practice target you can actually keep. Build a streak. Get a small celebration when you hit your goal. No XP gimmicks — just real metrics.',
    color: '#fb923c',
  },
  {
    icon: '🪜',
    title: 'Sequential learning path',
    description: 'A Duolingo-style path through the full UPSC syllabus, organised by subject and unit. Unlock topics as you complete them — never wonder "what next".',
    color: '#22d3ee',
  },
  {
    icon: '📊',
    title: 'Smart Strong / Focus pills',
    description: "Every topic on the path shows whether you're Strong (above 80% accuracy) or it's a Focus area (a subject you picked OR your accuracy dropped below 30%). At-a-glance status.",
    color: '#fbbf24',
  },
  {
    icon: '📈',
    title: 'Profile, heatmap & stats',
    description: 'Daily activity heatmap, accuracy graph, level system, subject-wise progress and a journey timeline showing every milestone — your complete UPSC dashboard.',
    color: '#ec4899',
  },
  {
    icon: '🧠',
    title: 'Tap-to-explain in notes',
    description: 'Every important term in your notes is tappable — Articles, committees, SC judgments, schemes, philosophers, frameworks — opens a popup with a senior-mentor-grade explanation.',
    color: '#c084fc',
  },
  {
    icon: '🆓',
    title: 'Free to start',
    description: 'Open the first 2 topics free, no signup, no card. See exactly how the notes, the practice and the mentor feel before deciding anything.',
    color: '#52d4a7',
  },
]

// ── Curated UPSC map catalogue ────────────────────────────────────────────────

interface MapCard {
  title: string
  description: string
  query: string
  icon: string
  color: string
  tags: string[]
}

interface MapSection {
  id: string
  label: string
  gs: string
  gsColor: string
  cards: MapCard[]
}

const CATALOGUE: MapSection[] = [
  {
    id: 'physical',
    label: 'Physical Geography',
    gs: 'GS-I',
    gsColor: '#2980b9',
    cards: [
      {
        title: 'Rivers of India',
        description: 'Major river systems, tributaries, and drainage basins across India.',
        query: 'Show all major rivers of India with their tributaries and drainage basins',
        icon: '🌊',
        color: '#2980b9',
        tags: ['Prelims', 'Mains'],
      },
      {
        title: 'Himalayan Ranges & Passes',
        description: 'Great Himalayas, Karakoram, and strategic passes like Nathu La, Shipki La.',
        query: 'Show Himalayan mountain ranges and all important passes of India for UPSC',
        icon: '⛰️',
        color: '#5a7bb5',
        tags: ['Prelims', 'Geography'],
      },
      {
        title: 'Western & Eastern Ghats',
        description: 'Biodiversity hotspots, peaks, rivers, and their UPSC significance.',
        query: 'Show Western Ghats and Eastern Ghats of India with major peaks and rivers',
        icon: '🌿',
        color: '#27ae60',
        tags: ['Prelims', 'Environment'],
      },
      {
        title: 'Soil Types of India',
        description: 'Alluvial, black, red, laterite, arid, and forest soils across regions.',
        query: 'Show different soil types of India — alluvial, black cotton, red, laterite, arid soils',
        icon: '🏜️',
        color: '#b07050',
        tags: ['Prelims', 'Agriculture'],
      },
      {
        title: 'Climate Zones of India',
        description: 'Koppen climate zones, monsoon patterns, and rainfall distribution.',
        query: 'Show climate zones and monsoon rainfall distribution of India',
        icon: '🌧️',
        color: '#0891b2',
        tags: ['Prelims', 'Geography'],
      },
      {
        title: 'Deccan Plateau',
        description: 'Peninsular India\'s plateau geography, rivers, and physical features.',
        query: 'Show the physical geography of Deccan Plateau with rivers and major features',
        icon: '🏔️',
        color: '#8a6a4a',
        tags: ['GS-I', 'Geography'],
      },
    ],
  },
  {
    id: 'history',
    label: 'Ancient & Medieval History',
    gs: 'GS-I',
    gsColor: '#e07b39',
    cards: [
      {
        title: 'Mauryan Empire',
        description: 'Chandragupta to Ashoka — India\'s first pan-Indian empire at its peak.',
        query: 'Show the Mauryan Empire under Ashoka with provinces, capitals, and rock edicts',
        icon: '🦁',
        color: '#e07b39',
        tags: ['Mains', 'Ancient'],
      },
      {
        title: 'Gupta Empire',
        description: 'The Golden Age of India — territory, trade routes, and cultural centres.',
        query: 'Show the Gupta Empire at its peak with major kingdoms, universities, and trade routes',
        icon: '☸️',
        color: '#c4953a',
        tags: ['Mains', 'Ancient'],
      },
      {
        title: 'Mughal Empire',
        description: 'From Babur to Aurangzeb — territorial expansion, battles, and capitals.',
        query: 'Show the Mughal Empire at its peak under Aurangzeb with provinces and major battles',
        icon: '🕌',
        color: '#7c5cba',
        tags: ['Mains', 'Medieval'],
      },
      {
        title: 'Maratha Empire',
        description: 'Shivaji to the Peshwas — the rise of the Maratha confederacy.',
        query: 'Show the Maratha Empire extent under the Peshwas with key battles and forts',
        icon: '⚔️',
        color: '#e06c5a',
        tags: ['Mains', 'Medieval'],
      },
      {
        title: 'Vijayanagara Empire',
        description: 'South India\'s powerful Hindu kingdom — from Hampi to the Battle of Talikota.',
        query: 'Show the Vijayanagara Empire with Hampi capital, territories, and important sites',
        icon: '🏛️',
        color: '#4a9e6e',
        tags: ['Mains', 'Medieval'],
      },
      {
        title: 'Ancient Trade Routes',
        description: 'Silk Road, maritime routes, and India\'s trade with Rome and Southeast Asia.',
        query: 'Show ancient Indian trade routes — Silk Road, maritime routes to Rome and Southeast Asia',
        icon: '🚢',
        color: '#0369a1',
        tags: ['GS-I', 'Ancient'],
      },
    ],
  },
  {
    id: 'colonial',
    label: 'Modern History & Freedom Struggle',
    gs: 'GS-I',
    gsColor: '#c0392b',
    cards: [
      {
        title: 'British India 1857',
        description: 'Colonial territory at the time of the First War of Independence.',
        query: 'Show British India colonial territory in 1857 at the time of the Revolt',
        icon: '🏴',
        color: '#c0392b',
        tags: ['Mains', 'Colonial'],
      },
      {
        title: 'Revolt of 1857',
        description: 'Key centres of the revolt — Meerut, Delhi, Lucknow, Jhansi, Kanpur.',
        query: 'Show the 1857 Revolt of India with all key battle centres and leaders',
        icon: '🔥',
        color: '#e63946',
        tags: ['Prelims', 'Mains'],
      },
      {
        title: 'Partition of India 1947',
        description: 'Radcliffe Line, princely states integration, and new international borders.',
        query: 'Show the partition of India in 1947 — Radcliffe Line, Pakistan, and princely states',
        icon: '🗓️',
        color: '#8e44ad',
        tags: ['Mains', 'Modern'],
      },
    ],
  },
  {
    id: 'political',
    label: 'Political Geography',
    gs: 'GS-II',
    gsColor: '#4f46e5',
    cards: [
      {
        title: 'India Political Map',
        description: 'All 28 states and 8 union territories with capitals.',
        query: 'Show India political map with all states union territories and their capitals',
        icon: '🗺️',
        color: '#4f46e5',
        tags: ['Prelims', 'Must-Know'],
      },
      {
        title: 'India\'s Neighbors',
        description: 'International borders with Pakistan, China, Bangladesh, and other neighbors.',
        query: 'Show India international borders and all neighboring countries with capitals',
        icon: '🌍',
        color: '#6d28d9',
        tags: ['Prelims', 'IR'],
      },
      {
        title: 'Northeast India',
        description: 'The Seven Sisters + Sikkim — states, capitals, and strategic significance.',
        query: 'Show northeast India seven sisters states with capitals and international borders',
        icon: '🏞️',
        color: '#0891b2',
        tags: ['Prelims', 'Geography'],
      },
      {
        title: 'Indian Ocean Region',
        description: 'India\'s maritime boundary, EEZ, island territories, and strategic chokepoints.',
        query: 'Show India maritime boundary EEZ Andaman Nicobar Lakshadweep and Indian Ocean',
        icon: '⚓',
        color: '#0369a1',
        tags: ['GS-II', 'IR'],
      },
    ],
  },
  {
    id: 'economic',
    label: 'Economic Geography',
    gs: 'GS-III',
    gsColor: '#27ae60',
    cards: [
      {
        title: 'Mineral Resources',
        description: 'Coal, iron ore, bauxite, copper, and manganese deposit locations.',
        query: 'Show coal iron ore bauxite copper and mineral deposits of India',
        icon: '⛏️',
        color: '#5d4037',
        tags: ['Prelims', 'Economy'],
      },
      {
        title: 'Major Ports of India',
        description: '13 major ports — from Kandla to Kolkata — and their trade significance.',
        query: 'Show all major ports of India with their location and trade significance',
        icon: '🚢',
        color: '#0369a1',
        tags: ['Prelims', 'Trade'],
      },
      {
        title: 'Agricultural Zones',
        description: 'Rice, wheat, cotton, sugarcane, and other crop-growing regions.',
        query: 'Show major agricultural zones of India — rice wheat cotton sugarcane jute regions',
        icon: '🌾',
        color: '#65a30d',
        tags: ['Prelims', 'Agriculture'],
      },
      {
        title: 'Major Dams of India',
        description: 'Bhakra Nangal, Hirakud, Sardar Sarovar — India\'s major dam projects.',
        query: 'Show all major dams of India with rivers and states',
        icon: '🏗️',
        color: '#2c3e50',
        tags: ['Prelims', 'Infrastructure'],
      },
      {
        title: 'National Highways',
        description: 'Golden Quadrilateral, North-South East-West corridors, and major NHs.',
        query: 'Show major national highways of India — Golden Quadrilateral and key corridors',
        icon: '🛣️',
        color: '#f39c12',
        tags: ['Prelims', 'Infrastructure'],
      },
      {
        title: 'Industrial Regions',
        description: 'Mumbai-Pune, Delhi-Meerut, Chota Nagpur, and other industrial belts.',
        query: 'Show major industrial regions and corridors of India',
        icon: '🏭',
        color: '#7f8c8d',
        tags: ['GS-III', 'Economy'],
      },
    ],
  },
  {
    id: 'environment',
    label: 'Environment & Ecology',
    gs: 'GS-III',
    gsColor: '#16a085',
    cards: [
      {
        title: 'Tiger Reserves',
        description: 'All Project Tiger reserves — from Jim Corbett to Sundarbans.',
        query: 'Show all tiger reserves of India under Project Tiger',
        icon: '🐯',
        color: '#e67e22',
        tags: ['Prelims', 'Environment'],
      },
      {
        title: 'National Parks',
        description: 'India\'s 106 national parks across all biographic zones.',
        query: 'Show all national parks of India',
        icon: '🌿',
        color: '#27ae60',
        tags: ['Prelims', 'Environment'],
      },
      {
        title: 'Ramsar Wetlands',
        description: 'India\'s internationally recognised wetlands of importance.',
        query: 'Show all Ramsar wetland sites of India',
        icon: '🦢',
        color: '#2980b9',
        tags: ['Prelims', 'Environment'],
      },
      {
        title: 'Biosphere Reserves',
        description: 'UNESCO-recognised biosphere reserves and biodiversity hotspots.',
        query: 'Show all UNESCO biosphere reserves of India',
        icon: '🌍',
        color: '#16a085',
        tags: ['Prelims', 'Environment'],
      },
      {
        title: 'Disaster Prone Zones',
        description: 'Earthquake, flood, cyclone, and drought-vulnerable regions of India.',
        query: 'Show disaster prone zones of India — earthquake cyclone flood drought areas',
        icon: '⚠️',
        color: '#e74c3c',
        tags: ['Prelims', 'Disaster Mgmt'],
      },
    ],
  },
  {
    id: 'prelims',
    label: 'Prelims Special',
    gs: 'Prelims',
    gsColor: '#d97706',
    cards: [
      {
        title: 'Nuclear Power Plants',
        description: 'All operational nuclear plants — Tarapur, Kudankulam, Rawatbhata and more.',
        query: 'Show all nuclear power plants of India',
        icon: '⚛️',
        color: '#e74c3c',
        tags: ['Prelims', 'Energy'],
      },
      {
        title: 'IIT Locations',
        description: 'All Indian Institutes of Technology across the country.',
        query: 'Show all IIT colleges in India with their locations',
        icon: '🎓',
        color: '#8e44ad',
        tags: ['Prelims', 'Education'],
      },
      {
        title: 'Thermal Power Plants',
        description: 'Major coal-based and thermal power stations of India.',
        query: 'Show major thermal power plants of India',
        icon: '🏭',
        color: '#7f8c8d',
        tags: ['Prelims', 'Energy'],
      },
      {
        title: 'Hydroelectric Projects',
        description: 'Major hydel projects — Tehri, Bhakra, Koyna and other power stations.',
        query: 'Show major hydroelectric power projects of India',
        icon: '💧',
        color: '#3498db',
        tags: ['Prelims', 'Energy'],
      },
    ],
  },
]

// ── Small helper: encode query for URL ────────────────────────────────────────

function encodeQuery(q: string) {
  return encodeURIComponent(q)
}

// ── MapCard component ─────────────────────────────────────────────────────────

function MapCardItem({ card }: { card: MapCard }) {
  const [hovered, setHovered] = useState(false)
  const href = `/map?q=${encodeQuery(card.query)}`

  return (
    <Link
      href={href}
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      className="group relative flex flex-col rounded-2xl overflow-hidden transition-all duration-200"
      style={{
        background: hovered ? `${card.color}12` : 'rgba(255,255,255,0.03)',
        border: `1px solid ${hovered ? `${card.color}50` : 'rgba(255,255,255,0.07)'}`,
        boxShadow: hovered ? `0 8px 32px ${card.color}18, 0 0 0 1px ${card.color}28` : 'none',
        transform: hovered ? 'translateY(-2px)' : 'none',
      }}
    >
      {/* Top accent bar */}
      <div style={{ height: 2.5, background: `linear-gradient(90deg, ${card.color}, ${card.color}55)` }} />

      <div className="p-4 flex flex-col flex-1">
        {/* Icon + title */}
        <div className="flex items-start gap-3 mb-2.5">
          <span
            className="w-10 h-10 rounded-xl flex items-center justify-center text-xl flex-shrink-0"
            style={{ background: `${card.color}18`, border: `1px solid ${card.color}35` }}
          >
            {card.icon}
          </span>
          <div className="flex-1 min-w-0">
            <h3 className="text-[13px] font-semibold text-white/90 leading-snug">{card.title}</h3>
            <div className="flex flex-wrap gap-1 mt-1">
              {card.tags.map(t => (
                <span
                  key={t}
                  className="text-[9px] font-bold uppercase tracking-wide px-1.5 py-0.5 rounded-md"
                  style={{ background: `${card.color}18`, color: `${card.color}cc` }}
                >
                  {t}
                </span>
              ))}
            </div>
          </div>
        </div>

        <p className="text-[11px] text-white/40 leading-relaxed flex-1">{card.description}</p>

        {/* Open button */}
        <div className="mt-3 flex items-center justify-between">
          <span className="text-[11px] font-semibold transition-colors"
            style={{ color: hovered ? card.color : 'rgba(255,255,255,0.25)' }}>
            Open on Map →
          </span>
          <span
            className="w-7 h-7 rounded-lg flex items-center justify-center transition-all"
            style={{
              background: hovered ? `${card.color}22` : 'rgba(255,255,255,0.05)',
              border: `1px solid ${hovered ? `${card.color}50` : 'rgba(255,255,255,0.08)'}`,
            }}
          >
            <svg width="11" height="11" viewBox="0 0 11 11" fill="none" stroke={hovered ? card.color : 'rgba(255,255,255,0.3)'} strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">
              <path d="M2 5.5h7M6.5 3l2.5 2.5L6.5 8" />
            </svg>
          </span>
        </div>
      </div>
    </Link>
  )
}

// ── FeatureCard ──────────────────────────────────────────────────────────────
// Each card carries an animated rotating conic-gradient border, a glowing
// icon orb, and a stagger-in fade-up entrance. Hovering brightens the
// border and lifts the card. Native to the futuristic register the
// journey app uses everywhere.

function FeatureCard({ feature, index }: { feature: JourneyFeature; index: number }) {
  const [hovered, setHovered] = useState(false)
  return (
    <div
      onMouseEnter={() => setHovered(true)}
      onMouseLeave={() => setHovered(false)}
      style={{
        position: 'relative',
        borderRadius: 18,
        padding: 1.25,
        background: hovered
          ? `conic-gradient(from var(--lp-angle, 0deg), ${feature.color}, ${feature.color}66, ${feature.color}, ${feature.color}66, ${feature.color})`
          : 'conic-gradient(from var(--lp-angle, 0deg), rgba(99,102,241,0.30), rgba(103,232,249,0.30), rgba(168,85,247,0.30), rgba(244,114,182,0.20), rgba(99,102,241,0.30))',
        animation: `lpRotate ${hovered ? '4s' : '12s'} linear infinite, lpFadeUp 700ms cubic-bezier(0.16,1,0.3,1) ${index * 60}ms both`,
        transition: 'transform 300ms cubic-bezier(0.16,1,0.3,1)',
        transform: hovered ? 'translateY(-3px)' : 'none',
      }}
    >
      <div
        style={{
          background: 'linear-gradient(180deg, #0a0a18 0%, #07071a 100%)',
          borderRadius: 16.75,
          padding: '20px 18px 18px',
          height: '100%',
          position: 'relative',
          overflow: 'hidden',
        }}
      >
        {/* Scanning sweep — only on hover */}
        {hovered && (
          <div style={{
            position: 'absolute', top: 0, bottom: 0, width: '40%',
            background: `linear-gradient(90deg, transparent, ${feature.color}14, transparent)`,
            animation: 'lpScan 2.4s ease-in-out infinite',
            pointerEvents: 'none',
            zIndex: 1,
          }} />
        )}

        {/* Icon orb — glowing tinted circle */}
        <div
          style={{
            width: 48, height: 48,
            borderRadius: 14,
            background: `radial-gradient(circle at 35% 30%, ${feature.color}22 0%, ${feature.color}10 60%, transparent 100%)`,
            border: `1px solid ${feature.color}40`,
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            fontSize: 22,
            marginBottom: 14,
            boxShadow: hovered
              ? `0 0 24px ${feature.color}40, inset 0 1px 0 rgba(255,255,255,0.06)`
              : `0 0 12px ${feature.color}22, inset 0 1px 0 rgba(255,255,255,0.04)`,
            transition: 'box-shadow 300ms',
            position: 'relative',
            zIndex: 2,
          }}
        >
          {feature.icon}
        </div>

        {/* Title */}
        <h3
          style={{
            fontSize: 15, fontWeight: 800,
            background: hovered
              ? `linear-gradient(135deg, #ffffff 0%, ${feature.color} 100%)`
              : 'linear-gradient(135deg, #ffffff 0%, #e0e7ff 100%)',
            WebkitBackgroundClip: 'text',
            WebkitTextFillColor: 'transparent',
            letterSpacing: '-0.015em',
            marginBottom: 6,
            lineHeight: 1.3,
            position: 'relative',
            zIndex: 2,
            transition: 'background 300ms',
          }}
        >
          {feature.title}
        </h3>

        {/* Description */}
        <p
          style={{
            fontSize: 12.5, lineHeight: 1.55,
            color: 'rgba(255,255,255,0.55)',
            margin: 0,
            position: 'relative',
            zIndex: 2,
          }}
        >
          {feature.description}
        </p>
      </div>
    </div>
  )
}

// ── Main Page ─────────────────────────────────────────────────────────────────

export default function HomePage() {
  const [activeSection, setActiveSection] = useState<string | null>(null)

  const visibleSections = activeSection
    ? CATALOGUE.filter(s => s.id === activeSection)
    : CATALOGUE

  const totalMaps = CATALOGUE.reduce((sum, s) => sum + s.cards.length, 0)

  return (
    <div className="min-h-screen bg-[#050510] text-white overflow-y-auto scrollbar-thin">

      {/* ── Futuristic keyframes — used by hero, feature cards & CTAs ─── */}
      <style>{`
        @property --lp-angle {
          syntax: '<angle>';
          initial-value: 0deg;
          inherits: false;
        }
        @keyframes lpRotate {
          to { --lp-angle: 360deg; }
        }
        @keyframes lpPulse {
          0%, 100% { filter: brightness(1) saturate(1); }
          50% { filter: brightness(1.30) saturate(1.20); }
        }
        @keyframes lpShimmer {
          0% { background-position: -200% center; }
          100% { background-position: 200% center; }
        }
        @keyframes lpFadeUp {
          from { opacity: 0; transform: translateY(18px); }
          to { opacity: 1; transform: translateY(0); }
        }
        @keyframes lpFloat {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-10px); }
        }
        @keyframes lpOrbBreathe {
          0%, 100% { opacity: 0.45; transform: scale(1); }
          50% { opacity: 0.75; transform: scale(1.06); }
        }
        @keyframes lpStarTwinkle {
          0%, 100% { opacity: 0.25; }
          50% { opacity: 0.85; }
        }
        @keyframes lpScan {
          0% { transform: translateX(-30%); opacity: 0; }
          15% { opacity: 1; }
          85% { opacity: 1; }
          100% { transform: translateX(330%); opacity: 0; }
        }
        @keyframes lpDot {
          0%, 100% { opacity: 0.6; }
          50% { opacity: 1; }
        }
        @keyframes lpCorePulse {
          0%, 100% { transform: scale(1); filter: drop-shadow(0 0 18px rgba(167,139,250,0.6)); }
          50% { transform: scale(1.04); filter: drop-shadow(0 0 32px rgba(167,139,250,0.9)); }
        }
      `}</style>

      {/* ── Nav ──────────────────────────────────────────────────────────── */}
      <nav className="sticky top-0 z-50 flex items-center justify-between px-6 py-3.5"
        style={{
          background: 'rgba(5,5,16,0.85)',
          backdropFilter: 'blur(24px)',
          WebkitBackdropFilter: 'blur(24px)',
          borderBottom: '1px solid rgba(167,139,250,0.10)',
        }}
      >
        <Link href="/" className="flex items-center gap-2.5">
          {/* Brand orb — animated rotating ring + glowing core */}
          <div className="relative w-9 h-9 flex-shrink-0" style={{ animation: 'lpFloat 6s ease-in-out infinite' }}>
            <div style={{
              position: 'absolute', inset: 0, borderRadius: 12,
              background: 'conic-gradient(from var(--lp-angle, 0deg), #6366f1, #67e8f9, #a78bfa, #f472b6, #6366f1)',
              animation: 'lpRotate 8s linear infinite',
              padding: 1.5,
            }}>
              <div style={{
                width: '100%', height: '100%', borderRadius: 11,
                background: '#050510',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 14,
              }}>
                <span style={{
                  background: 'linear-gradient(135deg, #c4b5fd, #67e8f9)',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                  fontWeight: 900, fontSize: 14,
                }}>P</span>
              </div>
            </div>
          </div>
          <div>
            <p className="text-sm font-bold text-white leading-none">PadhAI UPSC</p>
            <p className="text-[10px] leading-none mt-0.5"
              style={{
                background: 'linear-gradient(90deg, #c4b5fd, #67e8f9, #f9a8d4)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                fontWeight: 600,
              }}>Your AI guide for the entire UPSC syllabus</p>
          </div>
        </Link>

        <Link
          href="/journey"
          className="hidden md:flex items-center gap-2 px-4 py-2 rounded-xl text-[12px] font-bold text-white transition-all hover:scale-[1.03]"
          style={{
            background: 'linear-gradient(135deg, #6366f1, #8b5cf6, #67e8f9)',
            boxShadow: '0 4px 18px rgba(99,102,241,0.35), 0 0 0 1px rgba(255,255,255,0.06) inset',
          }}
        >
          <span style={{ fontSize: 13 }}>🚀</span>
          Start Journey
        </Link>
      </nav>

      {/* ── Hero ─────────────────────────────────────────────────────────── */}
      <div className="relative px-6 pt-20 pb-20 text-center overflow-hidden">
        {/* Background — multi-layer holographic field */}
        <div className="absolute inset-0 pointer-events-none">
          {/* Radial halo */}
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[500px] rounded-full"
            style={{
              background: 'radial-gradient(ellipse, rgba(99,102,241,0.16) 0%, rgba(168,85,247,0.10) 35%, transparent 70%)',
              animation: 'lpOrbBreathe 6s ease-in-out infinite',
            }} />
          {/* Floating orbs */}
          <div className="absolute top-12 left-[18%] w-32 h-32 rounded-full"
            style={{
              background: 'radial-gradient(circle, rgba(103,232,249,0.20), transparent 70%)',
              filter: 'blur(20px)',
              animation: 'lpFloat 10s ease-in-out infinite',
            }} />
          <div className="absolute top-32 right-[15%] w-40 h-40 rounded-full"
            style={{
              background: 'radial-gradient(circle, rgba(244,114,182,0.16), transparent 70%)',
              filter: 'blur(24px)',
              animation: 'lpFloat 12s ease-in-out infinite',
              animationDelay: '2s',
            }} />
          {/* Twinkling stars */}
          {[
            { top: '12%', left: '8%', delay: '0s' },
            { top: '22%', left: '85%', delay: '1.4s' },
            { top: '38%', left: '15%', delay: '0.8s' },
            { top: '55%', left: '78%', delay: '2.1s' },
            { top: '8%', left: '62%', delay: '1.6s' },
            { top: '70%', left: '22%', delay: '0.4s' },
            { top: '45%', left: '92%', delay: '2.6s' },
            { top: '60%', left: '5%', delay: '1.1s' },
          ].map((s, i) => (
            <span key={i} className="absolute w-1 h-1 rounded-full bg-white"
              style={{
                top: s.top, left: s.left,
                boxShadow: '0 0 6px rgba(255,255,255,0.8)',
                animation: `lpStarTwinkle 3s ease-in-out infinite`,
                animationDelay: s.delay,
              }} />
          ))}
        </div>

        <div className="relative z-10 max-w-3xl mx-auto">
          {/* Status pill — pulsing dot + AI label */}
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full mb-7 text-[11px] font-bold"
            style={{
              background: 'rgba(167,139,250,0.10)',
              border: '1px solid rgba(167,139,250,0.30)',
              color: '#c4b5fd',
              animation: 'lpFadeUp 700ms cubic-bezier(0.16,1,0.3,1) both',
              backdropFilter: 'blur(8px)',
            }}>
            <span className="relative w-1.5 h-1.5 rounded-full"
              style={{ background: '#a78bfa', boxShadow: '0 0 8px rgba(167,139,250,1)', animation: 'lpDot 1.6s ease-in-out infinite' }} />
            AI · 280+ TOPICS · UPSC 2025–26 · BUILT FOR ASPIRANTS
          </div>

          {/* Headline — gradient with shimmer */}
          <h1 className="text-4xl md:text-6xl font-black tracking-tight mb-5 leading-[1.05]"
            style={{ animation: 'lpFadeUp 800ms cubic-bezier(0.16,1,0.3,1) 0.1s both' }}>
            <span style={{
              background: 'linear-gradient(135deg, #ffffff 0%, #e0e7ff 50%, #c4b5fd 100%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              letterSpacing: '-0.02em',
            }}>
              Master the entire
            </span>
            <br />
            <span style={{
              background: 'linear-gradient(90deg, #818cf8 0%, #67e8f9 30%, #a78bfa 60%, #f9a8d4 100%)',
              backgroundSize: '200% 100%',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              animation: 'lpShimmer 6s linear infinite',
              letterSpacing: '-0.025em',
            }}>
              UPSC syllabus with AI
            </span>
          </h1>

          <p className="text-white/65 text-[15px] md:text-[17px] leading-relaxed mb-9 max-w-2xl mx-auto"
            style={{ animation: 'lpFadeUp 800ms cubic-bezier(0.16,1,0.3,1) 0.2s both' }}>
            A complete AI-powered learning journey through every UPSC topic — study notes, real PYQs, daily mentor tips, focus subjects, mains frameworks, interactive maps, streaks and more.{' '}
            <span style={{ color: '#c4b5fd', fontWeight: 600 }}>One app, end-to-end.</span>
          </p>

          {/* Primary + secondary CTAs */}
          <div className="flex items-center justify-center gap-3 flex-wrap mb-12"
            style={{ animation: 'lpFadeUp 800ms cubic-bezier(0.16,1,0.3,1) 0.3s both' }}>
            {/* PRIMARY — animated conic-gradient border with gradient fill */}
            <div className="relative" style={{ padding: 1.5, borderRadius: 16,
              background: 'conic-gradient(from var(--lp-angle, 0deg), #6366f1, #67e8f9, #a78bfa, #f472b6, #6366f1)',
              animation: 'lpRotate 6s linear infinite, lpPulse 4s ease-in-out infinite',
            }}>
              <Link
                href="/journey"
                className="group relative flex items-center gap-2.5 px-7 py-3.5 rounded-[14.5px] text-[15px] font-bold text-white transition-all"
                style={{
                  background: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 50%, #8b5cf6 100%)',
                  boxShadow: '0 8px 32px rgba(99,102,241,0.40), inset 0 1px 0 rgba(255,255,255,0.12)',
                }}
              >
                <span style={{ fontSize: 16 }}>🚀</span>
                Start Your Learning Journey
                <svg width="13" height="13" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" className="group-hover:translate-x-0.5 transition-transform">
                  <path d="M2 6h8M7 3l3 3-3 3" />
                </svg>
              </Link>
            </div>

            <a
              href="#features"
              className="flex items-center gap-2 px-5 py-3.5 rounded-2xl text-[13px] font-semibold text-white/70 hover:text-white transition-colors"
              style={{
                background: 'rgba(167,139,250,0.06)',
                border: '1px solid rgba(167,139,250,0.20)',
                backdropFilter: 'blur(8px)',
              }}
            >
              See all features
              <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round">
                <path d="M6 2v8M3 7l3 3 3-3" />
              </svg>
            </a>
          </div>

          {/* Stats row */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 max-w-2xl mx-auto"
            style={{ animation: 'lpFadeUp 800ms cubic-bezier(0.16,1,0.3,1) 0.45s both' }}>
            {[
              { value: '280+', label: 'UPSC Topics', glow: '#818cf8' },
              { value: '3000+', label: 'Real PYQs', glow: '#67e8f9' },
              { value: 'GS I–IV', label: 'Full syllabus', glow: '#a78bfa' },
              { value: 'Free', label: 'To start', glow: '#f9a8d4' },
            ].map(stat => (
              <div key={stat.label}
                className="px-3 py-3 rounded-xl text-center"
                style={{
                  background: 'rgba(255,255,255,0.025)',
                  border: '1px solid rgba(255,255,255,0.06)',
                  backdropFilter: 'blur(12px)',
                }}>
                <p className="text-xl md:text-2xl font-black"
                  style={{
                    background: `linear-gradient(135deg, #ffffff, ${stat.glow})`,
                    WebkitBackgroundClip: 'text',
                    WebkitTextFillColor: 'transparent',
                  }}>{stat.value}</p>
                <p className="text-[10px] text-white/40 mt-1 uppercase tracking-wider font-semibold">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ── Features section — the real headline of this page ─────────── */}
      <section id="features" className="relative max-w-7xl mx-auto px-4 md:px-6 pb-20">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full mb-4 text-[10px] font-bold uppercase tracking-widest"
            style={{ background: 'rgba(103,232,249,0.10)', border: '1px solid rgba(103,232,249,0.30)', color: '#67e8f9' }}>
            <span className="w-1 h-1 rounded-full bg-cyan-300" style={{ animation: 'lpDot 1.6s ease-in-out infinite' }} />
            What you get
          </div>
          <h2 className="text-3xl md:text-4xl font-black tracking-tight mb-3"
            style={{
              background: 'linear-gradient(135deg, #ffffff 0%, #c4b5fd 60%, #67e8f9 100%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              letterSpacing: '-0.02em',
            }}>
            Everything in your Learning Journey
          </h2>
          <p className="text-white/55 text-[14px] md:text-[15px] max-w-2xl mx-auto">
            Twelve features that work together as one AI study guide. Notes, practice, mentor, focus, frameworks, maps and more — built end-to-end for the UPSC syllabus.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {JOURNEY_FEATURES.map((f, i) => (
            <FeatureCard key={f.title} feature={f} index={i} />
          ))}
        </div>
      </section>

      {/* ── Maps preview band — framed as ONE feature ─────────────────── */}
      <section id="maps" className="relative max-w-7xl mx-auto px-4 md:px-6 pb-20">
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full mb-4 text-[10px] font-bold uppercase tracking-widest"
            style={{ background: 'rgba(52,211,153,0.10)', border: '1px solid rgba(52,211,153,0.30)', color: '#6ee7b7' }}>
            <span style={{ fontSize: 11 }}>🗺️</span>
            One feature: Interactive Maps
          </div>
          <h2 className="text-2xl md:text-3xl font-black tracking-tight mb-3"
            style={{
              background: 'linear-gradient(135deg, #ffffff 0%, #6ee7b7 100%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              letterSpacing: '-0.02em',
            }}>
            Browse {totalMaps}+ ready-to-explore maps
          </h2>
          <p className="text-white/50 text-[13px] md:text-[14px] max-w-xl mx-auto">
            Or build your own — ask the AI any question and it&apos;ll plot it live. These are the same maps your study notes link into when you tap{' '}
            <span style={{ color: '#6ee7b7', fontWeight: 600 }}>🗺️ Visualize on Map</span>.
          </p>

          {/* Mobile section filter */}
          <div className="flex md:hidden justify-center gap-2 mt-6 overflow-x-auto pb-2 scrollbar-thin">
            <button
              onClick={() => setActiveSection(null)}
              className="flex-shrink-0 px-3 py-1.5 rounded-lg text-[11px] font-semibold transition-all"
              style={{
                background: activeSection === null ? 'rgba(99,102,241,0.2)' : 'rgba(255,255,255,0.05)',
                color: activeSection === null ? '#a5b4fc' : 'rgba(255,255,255,0.4)',
                border: `1px solid ${activeSection === null ? 'rgba(99,102,241,0.4)' : 'rgba(255,255,255,0.08)'}`,
              }}
            >
              All
            </button>
            {CATALOGUE.map(s => (
              <button
                key={s.id}
                onClick={() => setActiveSection(activeSection === s.id ? null : s.id)}
                className="flex-shrink-0 px-3 py-1.5 rounded-lg text-[11px] font-semibold transition-all"
                style={{
                  background: activeSection === s.id ? `${s.gsColor}22` : 'rgba(255,255,255,0.05)',
                  color: activeSection === s.id ? s.gsColor : 'rgba(255,255,255,0.4)',
                  border: `1px solid ${activeSection === s.id ? `${s.gsColor}50` : 'rgba(255,255,255,0.08)'}`,
                }}
              >
                {s.gs}
              </button>
            ))}
          </div>
        </div>
      </section>

      {/* ── Map catalogue grid — lives inside the Maps section above ──── */}
      <div className="max-w-7xl mx-auto px-4 md:px-6 pb-24">
        {visibleSections.map(section => (
          <div key={section.id} className="mb-12">
            {/* Section header */}
            <div className="flex items-center gap-3 mb-5">
              <span
                className="text-[10px] font-bold uppercase tracking-widest px-2.5 py-1 rounded-lg"
                style={{ background: `${section.gsColor}20`, color: section.gsColor, border: `1px solid ${section.gsColor}35` }}
              >
                {section.gs}
              </span>
              <h2 className="text-[16px] font-bold text-white/90">{section.label}</h2>
              <div className="flex-1 h-px" style={{ background: 'rgba(255,255,255,0.06)' }} />
              <span className="text-[11px] text-white/25">{section.cards.length} maps</span>
            </div>

            {/* Cards grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
              {section.cards.map(card => (
                <MapCardItem key={card.title} card={card} />
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* ── Final CTA — futuristic journey close ─────────────────────── */}
      <section id="journey" className="relative py-24 px-4 overflow-hidden border-t border-white/[0.04]">
        {/* Background — radial halo + floating orbs */}
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[400px] rounded-full"
            style={{
              background: 'radial-gradient(ellipse, rgba(167,139,250,0.18) 0%, rgba(99,102,241,0.10) 35%, transparent 70%)',
              animation: 'lpOrbBreathe 6s ease-in-out infinite',
            }} />
          <div className="absolute top-8 left-[20%] w-32 h-32 rounded-full"
            style={{
              background: 'radial-gradient(circle, rgba(103,232,249,0.20), transparent 70%)',
              filter: 'blur(28px)',
              animation: 'lpFloat 11s ease-in-out infinite',
            }} />
          <div className="absolute bottom-12 right-[18%] w-40 h-40 rounded-full"
            style={{
              background: 'radial-gradient(circle, rgba(244,114,182,0.18), transparent 70%)',
              filter: 'blur(30px)',
              animation: 'lpFloat 13s ease-in-out infinite',
              animationDelay: '1.5s',
            }} />
        </div>

        <div className="relative z-10 max-w-3xl mx-auto">
          {/* Outer rotating conic-gradient frame */}
          <div className="relative mx-auto" style={{
            padding: 1.75, borderRadius: 28, maxWidth: 720,
            background: 'conic-gradient(from var(--lp-angle, 0deg), #6366f1, #67e8f9, #a78bfa, #f472b6, #6366f1)',
            animation: 'lpRotate 7s linear infinite, lpPulse 4.5s ease-in-out infinite',
          }}>
            <div style={{
              borderRadius: 26.25,
              background: 'linear-gradient(180deg, #0a0a18 0%, #06061a 100%)',
              padding: '40px 28px 36px',
              textAlign: 'center',
              position: 'relative',
              overflow: 'hidden',
            }}>
              {/* Subtle scan line */}
              <div style={{
                position: 'absolute', top: 0, bottom: 0, width: '40%',
                background: 'linear-gradient(90deg, transparent, rgba(167,139,250,0.06), transparent)',
                animation: 'lpScan 6s ease-in-out infinite',
                pointerEvents: 'none',
              }} />

              {/* Pulsing dot + label */}
              <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full mb-5 text-[10px] font-bold uppercase tracking-widest"
                style={{ background: 'rgba(167,139,250,0.10)', color: '#c4b5fd', border: '1px solid rgba(167,139,250,0.30)' }}>
                <span className="w-1.5 h-1.5 rounded-full"
                  style={{ background: '#a78bfa', boxShadow: '0 0 8px rgba(167,139,250,1)', animation: 'lpDot 1.6s ease-in-out infinite' }} />
                Ready when you are
              </div>

              <h2 className="text-3xl md:text-5xl font-black tracking-tight mb-4 leading-[1.05]"
                style={{ position: 'relative', zIndex: 2 }}>
                <span style={{
                  background: 'linear-gradient(135deg, #ffffff 0%, #e0e7ff 50%, #c4b5fd 100%)',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                  letterSpacing: '-0.02em',
                }}>
                  Start your UPSC
                </span>
                <br />
                <span style={{
                  background: 'linear-gradient(90deg, #818cf8, #67e8f9, #a78bfa, #f9a8d4)',
                  backgroundSize: '200% 100%',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent',
                  animation: 'lpShimmer 5s linear infinite',
                  letterSpacing: '-0.025em',
                }}>
                  journey today
                </span>
              </h2>
              <p className="text-white/60 text-[14px] md:text-[16px] leading-relaxed mb-8 max-w-lg mx-auto"
                style={{ position: 'relative', zIndex: 2 }}>
                Free to start. No card. No signup wall. Open the first 2 topics and feel how the notes, the practice and your AI mentor work together.
              </p>

              {/* Big rotating-border CTA */}
              <div className="inline-block relative" style={{
                padding: 1.5, borderRadius: 18,
                background: 'conic-gradient(from var(--lp-angle, 0deg), #6366f1, #67e8f9, #a78bfa, #f472b6, #6366f1)',
                animation: 'lpRotate 5s linear infinite',
                position: 'relative', zIndex: 2,
              }}>
                <Link
                  href="/journey"
                  className="group flex items-center gap-3 px-8 py-4 rounded-[16.5px] text-[15px] md:text-[16px] font-black text-white transition-all"
                  style={{
                    background: 'linear-gradient(135deg, #4f46e5 0%, #7c3aed 50%, #8b5cf6 100%)',
                    boxShadow: '0 10px 36px rgba(99,102,241,0.45), inset 0 1px 0 rgba(255,255,255,0.12)',
                    letterSpacing: '0.01em',
                  }}
                >
                  <span style={{ fontSize: 18 }}>🚀</span>
                  Begin Your Journey
                  <svg width="14" height="14" viewBox="0 0 12 12" fill="none" stroke="currentColor" strokeWidth="2.6" strokeLinecap="round" strokeLinejoin="round" className="group-hover:translate-x-0.5 transition-transform">
                    <path d="M2 6h8M7 3l3 3-3 3" />
                  </svg>
                </Link>
              </div>

              {/* Trust line */}
              <p className="text-[11px] text-white/30 mt-6 font-semibold uppercase tracking-widest"
                style={{ position: 'relative', zIndex: 2 }}>
                Notes · PYQs · Mentor · Maps · Frameworks · Streaks
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── Footer ───────────────────────────────────────────────────────── */}
      <footer className="border-t border-white/[0.04] px-6 py-6 flex flex-col sm:flex-row items-center justify-between gap-2 text-[11px]"
        style={{ background: 'rgba(5,5,16,0.6)' }}>
        <span style={{
          background: 'linear-gradient(90deg, #c4b5fd, #67e8f9, #f9a8d4)',
          WebkitBackgroundClip: 'text',
          WebkitTextFillColor: 'transparent',
          fontWeight: 700,
        }}>PadhAI UPSC · Your AI study guide for the entire syllabus</span>
        <span className="text-white/25">Notes · PYQs · Mentor · Maps · Frameworks · Free</span>
      </footer>
    </div>
  )
}
